clear:

delete:
  fields:
    entity_id:
      example: sun.sun
      required: true
      selector:
        entity:
          multiple: true

delete_regex:
  fields:
    entity_id_regex:
      example: light.living_room.*
      required: true
      selector:
        text:

delete_variable:
  fields:
    name:
      example: counter
      required: true
      selector:
        text:

delete_variable_regex:
  fields:
    regex:
      example: counter_.*
      required: true
      selector:
        text:

set_variable:
  fields:
    name:
      example: counter
      required: true
      selector:
        text:
    value:
      example: "3"
      required: false
      selector:
        text:
    value_entity:
      required: false
      selector:
        entity:
    use_current_time:
      default: false
      required: false
      selector:
        boolean:

save_state:
  fields:
    entity_id:
      example: sun.sun
      required: true
      selector:
        entity:
          multiple: true

restore_state:
  fields:
    entity_id:
      example: sun.sun
      required: true
      selector:
        entity:
          multiple: true
    delete_after_run:
      example: false
      default: true
      required: false
      selector:
        boolean:
    transition:
      required: false
      selector:
        number:
          min: 0
          max: 300
          unit_of_measurement: s
